"""empty message

Revision ID: e87b51e02f0e
Revises: 
Create Date: 2019-08-04 20:11:03.936277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e87b51e02f0e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
